# product environment on aws ec2
# application-prod.properties
spring.application.name=STYLiSH
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/new_stylish
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=ubuntu
spring.datasource.password=mysqlpwd123

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

upload.path=/home/ubuntu/image
upload.domain=http://35.74.181.119

