# local development on macOS
# application-dev.properties
spring.application.name=STYLiSH
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/new_stylish
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Max33476129

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

upload.path=/Users/maxchauo/Pictures/new_stylish/images
upload.domain=http://localhost:8080
